server:
  port: 8761

      
eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    service-url: 
      defaultzone: ${DISCOVERY_URL:http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
  
spring:
  application:
    name: eurekaserver
  boot:
    admin:
      context-path: /admin  
    
     